#!/bin/bash
set -x


if [ "$IFACE" = wlan0 ]; then
	#/usr/bin/curl -F "upfile=@/home/pi/kasadakanet/file.txt" 192.168.77.1:8080
	
	#QUERY=$(cat /home/pi/kasadakanet/query.txt)
	#/usr/bin/curl 192.168.77.1:8910/demo/sparql/ --data-urlencode "query=${QUERY}" > /home/pi/kasadakanet/queryresult.rdf
fi
