#!/bin/bash
set -x


if [ "$IFACE" = wlan0 ]; then
	echo "wlan0: Just detected wifi connection" >> /etc/network/connectionlog.txt
	#/bin/bash /etc/network/curltest.sh
	#/bin/bash /etc/network/curlcliopatria.sh
fi
